// AUTO-GENERATED by scripts/build-carousel.js — do not edit manually
// Re-generate by running: node scripts/build-carousel.js
var PRODUCT_IMAGES = {
  "amor-red": [],
  "angel-white": [],
  "dhalia-pink": [],
  "donna-champagne": [],
  "flora-pink": [],
  "the-aria": [],
  "the-pearl": [],
  "veronicas-garden": []
};
